apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:h6+igK1sHI6zCpr/kGFNz1SSfAv69Q8MkpwIQYROQXGLoM79,iv:LwfwgiGCdIQpUCvvoOtuoZTvBoNPZc+o2CKEtHSxomQ=,tag:HJozjrY0ft3lwxSQP4BLyQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:mXGKY2ZejxOn/2M5mKdHKiZp5CiuVAgk45PL6bWix+R9xMmVtYCu5EVkiHn7Unf3Lb99nxciYjC64jBVvADhcmpods+qAhmSomhZ/BvHrjAq7mHkC1kc34eZjDoatJFrLR3y8mGEvRrL9HIdGE9O2KQNcJaFKW95fzjsvFWjiDxcPN2W5ePEFCX+wRJosjt9gKBPoj3J9WfmWtYt457qYsC6g7qDEoA5Ij9v5Cgn+A==,iv:zEStbDIqyAaYHHW5jcfkXiH2iYVrTBYPMg/5nYUsd8Y=,tag:6GbVhjYYlipX6teq8Uahpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbTJHbnJMM05PMFMra3hu
            b1FxNjh6RmZscHRISU1jMHd0SGZwU3NSdlNZCk52YXpaSFRyQjh2Sng0VkdBdFdD
            TmFvV3ZMdW80bGVIWUhnQ1hmYkVWU0kKLS0tIEtGYi9pT1F4YjZOU2RzVTNTWitu
            RHY0VVhPaDZVV2pTK1BsYjlDdTc2S2MKSmaTqRlTvw1A7XsnxpWutH7aQLC7z3n3
            9VmbOtoQ5uLck5jCqkWOf7bAgu5SdqENi8DacU53WYxQaJYxc43i0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-10T20:17:52Z"
    mac: ENC[AES256_GCM,data:rmwyf2fd0piOnEa5YNUL4uk0NzmviPxa1RaywlJjfdnZ8rMUrHwci3amQLptp0xKUXqJ9h4VlaaeA+ACxL8UF4xmA+E4wZpokTkMrt1wF4O4xSP4554ySLQugjBzK+pb431PsvzydwqwzksQQgHzJ6XledC9VkdB2/vXdiSHzGQ=,iv:nGz+bt55Q2HNb8JbM6713ZHNwbM9Nkda0M9xS5Y227M=,tag:LIDz7apXc5+IovyeAx5RIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
