apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:nwn5318iZ5o7ka5S3yglINfgZtbDxIm78orZ542vVX3RpG9OFDH0hg==,iv:GDmt3+sX9x8N5ex69BU+6R1fBVyJsb+rZn6QLIwslqc=,tag:Cw4qUWqAUrwZOJKlVyCK4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUWJ0RzRtcitkOVBMU2gr
            Uld5SDdUWnNCenhqZ0p5ZEYvWnUrNURlRWc4Cm5uQWtVenBTZFRzZFhERDR3WG9q
            aElvak4vMTBkMmk5SjNDQm0wVGgzVlkKLS0tIGxkOGg5NWVMK3h3Tkoyd1duTlhC
            SEIwR1RMQkxCZC9YNGtsSU44OGJESjAK1YVRzsJRlZiQ74V5Uxb0mCVzM6RqGtjL
            DAg6YOhg6ZqvO77U/LsQVqx/EYGoGzvKz8+Jl4Z6VneqQIv1TbGvqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-10T18:13:22Z"
    mac: ENC[AES256_GCM,data:4OhaOl6C1AVmWCjI+ylbnWIbAoe/c8dI1aJAQ1CxcADN6PKeZmZe4qIydarvrZwU3fkXVF/yVlaNP5N7Lmjzdy60PukahdD2ZXD3cGUzJUy0aCfI6HQZKxs12bmOIJ1j0UlvHbo39yuGBl7IFfT9y6Fa72jBQ3aYZTX3DM+1Rx4=,iv:MKjkjWIjAAAW0nUZeyZvx838iKX5s432ydVIFx+3ztI=,tag:U8+Lr7xkOktEDpbml3CDew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
