apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:DFj9iK3BJMhDF7IhhEMkLkCFF61B1dXdwIi8wf+QOP1x+g5U5V8VUNG1Qh11hkIXV+ugcLMmgPfbn4fLaSIwzqw3uK2vWT22oj9mtKG3wwjMJ5odhiRM8b+8tcVlbQ==,iv:P42q9LZHF8h2FJr+BYNj1TR2tx+Fp6vMzAGV1ntiF1k=,tag:NR5yDde2LJzVVUWSMdCZRA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4sNht9XVbRZI/0MEaw==,iv:ieGey7JUGYeFuemliMSGEGrsJYnDh/16kRrXyroXtrs=,tag:hVdgyg4HqcWL2UK5H9kYSA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GckhqjpNbR8TvLj2ndKvyojm,iv:ZL29RH4Z3vAghyEatPILYe0YZSDwUxcI9kuaAp3r/QI=,tag:hekm6bbAilAEb7jsYAKhEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rw+5ubfvNUoviBiuZwhjzrA/3IgSCp1YZ7jcb/TXHbpe5hYW,iv:JsrcZ5VXGlCKzDjr4mE0r1poqDG9rV2B8HuBo0VALO8=,tag:G3ZXfiE2bEmXnqlmHUSABA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UHhueVA5blR2OGpUTGFj
            M2ZRZS83WXdoaWJxQklYS1dSL2hMbUcraEdnCnFOS0paWGp4YkN0MHF6TGpUazBi
            bDc3UmhQbkVyWEtMUDdvc2NST0lITncKLS0tIHNwWlhicnRNWmZkMEhzMG9sbHhS
            TTBNaFZRbGg0L2cyTHVPMmIvZHVvRzgKR7dNidEovIzr2G9JUMRuWtEr+ddvYA5n
            oNIbZcv1Mwttn/aUd5kIvgnz8GWU6wvoX1mo4RV+i2sUp00nGdOlyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-10T20:17:52Z"
    mac: ENC[AES256_GCM,data:kOl2fwIUnaxZ5+wJPSqCW25inwRk40iODbHE6NiLCnxCkwp+F67VU3bG7KQJPjX+2uxC/Ds+xBJmLOCrG7F9alTdvJJxSr+/qrCd5Voy+oOLJBwvK80UcsfIakWiQOxvx2iQYD83tbJfHbczasHu1ac7UH0u+tvfT7L75pW/nH8=,iv:hPi99hbam51NN+u5X0j5ITuhzDXwNFlQDm8ya32kzCI=,tag:Q14+hGbZfpQuzmrjdehupQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
