apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:YUmDwsSxP5/sxhka4WhyenlEUGNT9q9r/XLD8dy8aPi7YcBIJzzSug==,iv:K0e4mT7bHSsdGO6XcTn6lJApRyHSlE8aHHwHIo5t2ZE=,tag:d/3bqGU7V7OZs13DfcKByw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fuxe2g32ufyqyw4s82fxxymcs47wlt7p3h5qm5kg0t5djnqqza2qjzcl4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN1ZZK284VmFzNTF4WFZm
            QzczOE11UzFDVDdaQVpUVStRMEUxVHlvQ1VJCkR3R3FBRzVpQmN5Mi9mZUhWR0lG
            NVdzMGpsNGV6dnlIY3F2djhuVlNDY2sKLS0tIHVSVkFiNjY4VzVSMjRtMkNtRTdZ
            TEJrUmF4L2xCcXk2UkY0S2l0eThGMTQK+KkiDbk2Xusb1ymPyj0EyHQf4RmOXIti
            IRrX0zDNckRlXk/3HUrilFOIB7NJ94p+8dyQrsBQCZbH5aKa8vaf1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-10T18:13:23Z"
    mac: ENC[AES256_GCM,data:WGAl3eO44hPVIcfx80I0MsaP5/Mg67w5cl8AkFlJxDqxb5hot/RttfFLa+jmQEn+MYilwhMQYG3q/LfC7bvy4TJS797A5yHmezMqUGiEtW5p6DKRtoZXqskgd8oHpj//hKlRAqHrkQZbnj/WOVozDiDz8PFk44XMw+uyvDFK1UM=,iv:l8AR7VXCCXHERluIeTzZmpNbK34nzioN936VTdhH/qA=,tag:hzdJJc4oe0vkIcjSSsHHzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
